language: node_js
node_js:
  - "8.11.3"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

after_success:
  - npx semantic-release
